CREATE TABLE public.user (
    id int GENERATED BY DEFAULT AS IDENTITY,
    username text NOT NULL,
    fullname text NOT NULL,
    email text NOT NULL,
    password text NOT NULL,
    tweet text NOT NULL,

);

ALTER TABLE ONLY public.user
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);

-- insert data
INSERT INTO public.user (username, fullname, email, password, tweet) VALUES ('dahlanprasetya', 'Dahlan Prasetya', 'dahlan@mail.com', 'dahlan123', 'aduh pengen es krim');
INSERT INTO public.user (username, fullname, email, password, tweet) VALUES ('coki', 'Coki Pardede', 'coki@haha.com', 'coki123', 'nada nada nada muncul lah');
INSERT INTO public.user (username, fullname, email, password, tweet) VALUES ('rigen', 'Rigen Wakwaw', 'rigen@haha.com', 'rigen123', 'coki bau');